<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Appointment details · ClinicManager</title><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config = { theme: { extend: { colors: { ink: '#102a43', ocean: '#1677a8', line: '#d8e4ec' } } } };</script></head>
<body class="min-h-screen bg-[#f7fafc] text-ink antialiased">
<header class="border-b border-line bg-white"><div class="mx-auto flex max-w-5xl items-center justify-between px-5 py-5 sm:px-8"><a href="${ctx}/patient/appointments" class="flex items-center gap-3 text-lg font-semibold tracking-tight"><span class="grid h-9 w-9 place-items-center rounded-xl bg-ink text-xl text-[#8fe4d8]">+</span>ClinicManager</a><a href="${ctx}/patient/appointments" class="text-sm font-semibold text-ocean hover:text-ink">← All appointments</a></div></header>
<main class="mx-auto max-w-5xl px-5 py-10 sm:px-8"><div class="mb-8"><p class="mb-2 text-sm font-semibold uppercase tracking-[.18em] text-ocean">Appointment #${appointment.id}</p><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="text-3xl font-semibold tracking-tight">Appointment details</h1><p class="mt-2 text-sm text-slate-500">Your consultation information in one place.</p></div><c:choose><c:when test="${appointment.statusLabel == 'PLANNED'}"><span class="w-fit rounded-full bg-sky-50 px-3 py-1.5 text-xs font-semibold text-sky-700">PLANNED</span></c:when><c:when test="${appointment.statusLabel == 'DONE'}"><span class="w-fit rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">DONE</span></c:when><c:otherwise><span class="w-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">${appointment.statusLabel}</span></c:otherwise></c:choose></div></div>
<section class="grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div class="rounded-2xl border border-line bg-white p-6 shadow-[0_18px_50px_rgba(16,42,67,.06)] sm:p-8"><div class="mb-8 flex items-start gap-4"><div class="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#e9f7f5] text-xl font-semibold text-[#167268]">DR</div><div><p class="text-sm text-slate-500">Consultation with</p><h2 class="mt-1 text-xl font-semibold">${appointment.doctorFullName}</h2><p class="mt-1 text-sm text-slate-500">Healthcare professional</p></div></div><div class="grid gap-6 border-t border-line pt-7 sm:grid-cols-2"><div><p class="text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Date &amp; time</p><p class="mt-2 font-medium text-ink">${appointment.dateStartingTime}</p></div><div><p class="text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Appointment type</p><p class="mt-2 font-medium text-ink">${appointment.typeLabel}</p></div><div class="sm:col-span-2"><p class="text-xs font-semibold uppercase tracking-[.12em] text-slate-400">Reason for visit</p><p class="mt-2 leading-6 text-slate-600"><c:choose><c:when test="${not empty appointment.reason}">${appointment.reason}</c:when><c:otherwise>No reason was provided.</c:otherwise></c:choose></p></div></div></div><aside class="rounded-2xl border border-line bg-white p-6 shadow-[0_18px_50px_rgba(16,42,67,.06)] sm:p-8"><div class="mb-6 flex items-center justify-between"><div><p class="text-sm font-semibold uppercase tracking-[.12em] text-ocean">Clinical record</p><h2 class="mt-2 text-xl font-semibold">Medical notes</h2></div><span class="grid h-10 w-10 place-items-center rounded-xl bg-[#f0f5f8] text-slate-500">≡</span></div><c:choose><c:when test="${appointment.hasMedicalNote}"><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p class="font-semibold text-emerald-800">Note available</p><p class="mt-1 text-sm leading-6 text-emerald-700">Your doctor has added a medical note for this appointment.</p><a href="#medical-note" class="mt-4 inline-flex text-sm font-semibold text-emerald-800 hover:underline">View note <span class="ml-1">→</span></a></div></c:when><c:otherwise><div class="rounded-xl border border-line bg-[#fbfdfe] p-4"><p class="font-semibold text-ink">No medical note yet</p><p class="mt-1 text-sm leading-6 text-slate-500">Medical notes become available after the consultation is completed.</p></div></c:otherwise></c:choose><div class="mt-7 border-t border-line pt-6"><p class="text-xs leading-5 text-slate-400">Medical notes are private clinical information and should only be shared with trusted healthcare professionals.</p></div></aside></section></main>
</body>
</html>