<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My appointments · ClinicManager</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>tailwind.config = { theme: { extend: { colors: { ink: '#102a43', ocean: '#1677a8', line: '#d8e4ec' } } } };</script>
</head>
<body class="min-h-screen bg-[#f7fafc] text-ink antialiased">
<header class="border-b border-line bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><a href="${ctx}/patient/appointments" class="flex items-center gap-3 text-lg font-semibold tracking-tight"><span class="grid h-9 w-9 place-items-center rounded-xl bg-ink text-xl text-[#8fe4d8]">+</span>ClinicManager</a><div class="flex items-center gap-4"><span class="hidden text-sm text-slate-500 sm:inline">Patient portal</span><a href="${ctx}/auth/login" class="rounded-lg border border-line px-3 py-2 text-sm font-medium text-slate-600 transition hover:border-slate-300 hover:text-ink">Sign out</a></div></div></header>
<main class="mx-auto max-w-7xl px-5 py-10 sm:px-8">
    <div class="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="mb-2 text-sm font-semibold uppercase tracking-[.18em] text-ocean">Patient dashboard</p><h1 class="text-3xl font-semibold tracking-tight">My appointments</h1><p class="mt-2 text-sm text-slate-500">Keep track of your upcoming visits and consultation history.</p></div><a href="${ctx}/patient/appointments/new" class="inline-flex items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-[#183d5b]">Book an appointment <span class="text-lg leading-none">+</span></a></div>
    <c:if test="${not empty formError}"><div role="alert" class="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">${formError}</div></c:if>
    <section class="overflow-hidden rounded-2xl border border-line bg-white shadow-[0_18px_50px_rgba(16,42,67,.06)]">
        <div class="flex items-center justify-between border-b border-line px-5 py-5 sm:px-7"><div><h2 class="font-semibold">Appointment history</h2><p class="mt-1 text-sm text-slate-500">${appointments.size()} appointment<c:if test="${appointments.size() != 1}">s</c:if> found</p></div><span class="rounded-full bg-mint px-3 py-1.5 text-xs font-semibold text-[#167268]">Up to date</span></div>
        <c:choose><c:when test="${empty appointments}"><div class="px-6 py-16 text-center"><div class="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-[#e9f7f5] text-2xl text-[#167268]">+</div><h3 class="font-semibold">No appointments yet</h3><p class="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">When you book a visit, it will appear here with the doctor, specialty, and status.</p><a href="${ctx}/patient/appointments/new" class="mt-5 inline-flex rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white">Find a time</a></div></c:when><c:otherwise><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left"><thead class="border-b border-line bg-[#fbfdfe]"><tr class="text-xs uppercase tracking-[.12em] text-slate-400"><th class="px-7 py-4 font-semibold">Doctor</th><th class="px-5 py-4 font-semibold">Date &amp; time</th><th class="px-5 py-4 font-semibold">Type</th><th class="px-5 py-4 font-semibold">Status</th><th class="px-7 py-4 text-right font-semibold">View</th></tr></thead><tbody class="divide-y divide-line"><c:forEach items="${appointments}" var="item"><tr class="transition hover:bg-[#fbfdfe]"><td class="px-7 py-5"><p class="font-semibold text-ink">${item.doctorFullName}</p><p class="mt-1 text-sm text-slate-500">${item.specialtyName}</p></td><td class="px-5 py-5 text-sm text-slate-600">${item.dateTime}</td><td class="px-5 py-5 text-sm text-slate-600">${item.typeLabel}</td><td class="px-5 py-5"><c:choose><c:when test="${item.statusLabel == 'PLANNED'}"><span class="inline-flex rounded-full bg-sky-50 px-3 py-1.5 text-xs font-semibold text-sky-700">PLANNED</span></c:when><c:when test="${item.statusLabel == 'DONE'}"><span class="inline-flex rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-700">DONE</span></c:when><c:otherwise><span class="inline-flex rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600">${item.statusLabel}</span></c:otherwise></c:choose></td><td class="px-7 py-5 text-right"><a href="${ctx}/patient/appointments/${item.id}" class="text-sm font-semibold text-ocean hover:text-ink">Details <span aria-hidden="true">→</span></a></td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose>
    </section>
</main>
</body>
</html>